Font Size
engaging-computing/MYR pull request #532
Opened 2022-01-07 23:22 UTC by jf-kelly

Added font size functionality for the editor. A dropdown menu button can be found below the editor next to the keyboard shortcuts button.

2022-01-10 14:57 UTC, Jlu18 requested changes
Please change the merging branch to "dev" and fixed the failed unit test.

2022-01-10 18:49 UTC, kdvalin requested changes
~~Unit tests also need to be fixed~~.  Missing backend PR for user profiles.

2022-01-10 18:49 UTC, kdvalin commented on src/actions/userActions.js
> +}
Isn't this @bryanmontalvan's Dark mode?

If you're relying on his work for a user profile, maybe we should split those changes out such that you don't need to add his code before it's in a finished state

2022-01-10 18:49 UTC, kdvalin commented on src/components/editor/FontSize.js
> +                            <option value={50}>50</option>
Are we only aiming to support these font sizes?

There should be a better way to have these auto-populate without having to manually add `<option>`s

2022-01-10 18:49 UTC, kdvalin commented on src/containers/Collection.js
> +    userSettings:state.user.settings,
add a space between the colon and `state`.  

Reminding myself to update esdoc rules on this @kdvalin.

2022-01-10 18:49 UTC, kdvalin commented on src/containers/Guided.js
> +    usersettings:state.user.settings,
Same as previous comment

2022-01-10 18:49 UTC, kdvalin commented on src/containers/Ide.js
> +    usersettings:state.user.settings,
Same as previous comment

2022-01-10 18:49 UTC, kdvalin commented on src/reducers/user.js
> +                    fontSize: action.newFont
rename the `newFont` attribute to something more indicative of what it is, such as `fontSize`

2022-01-10 19:16 UTC, kdvalin approved these changes
Approving pending backend PR for User profile API

2022-01-13 13:57 UTC, Jlu18 approved these changes

2022-02-02 18:57 UTC, Jlu18 requested changes
I noticed that user settings were not updated the fontsize is changed. You have to use componentDidUpdate to check if usersettings is updated on redux and send the settings to backed accordingly.

2022-02-16 18:31 UTC, kdvalin approved these changes

2022-02-16 18:31 UTC, merged