Import/Export Feature
engaging-computing/MYR pull request #534
Opened 2022-01-10 18:40 UTC by kdvalin

This PR allows for scenes to be exported to a user's device and then imported at a later date.

2022-01-13 14:15 UTC, Jlu18 commented
Can you update the backend [import/export PR](https://github.com/engaging-computing/MYR-backend/pull/160) so I can test it on my machine.

2022-01-14 15:37 UTC, Jlu18 requested changes
The import and export options should be disabled (or hide away) if the user is not logged in, as well as if the user is on example project tab (since it doesn't seem like you can export those)

2022-01-14 15:37 UTC, Jlu18 commented on src/components/structural/header/ProjectView.js
> +                                    onChange={(e) => this.props.importFunc(this.props.user.uid, e.target.files)}
Also returns error when user is not logged in.

2022-01-14 15:37 UTC, Jlu18 commented on src/components/structural/header/ProjectView.js
> +            </MenuItem>
Example project also has an option to export the scene but unable to.

2022-01-14 15:37 UTC, Jlu18 commented on src/components/structural/header/ProjectView.js
> +                                    onChange={(e) => this.props.importFunc(this.props.user.uid, e.target.files)}
Probably hide the option if user is not logged in (or import the scene without saving as a scene)

2022-01-14 15:37 UTC, Jlu18 commented on src/components/structural/header/ProjectView.js
> +                                <input
Is there any reason why this input tag is outside of the import Button? It seems to be working fine but I think it should be a child of the Button.

2022-02-02 16:34 UTC, Jlu18 requested changes

2022-02-02 16:34 UTC, Jlu18 commented on src/components/structural/header/ProjectView.js
> +            </MenuItem>
Exporting example scene still gave 404 error. Is this intentional or do we want to give user option to export the example scene?

2022-02-03 21:05 UTC, kdvalin commented
Bumping to next version since I needed to update AFrame

2022-02-10 16:19 UTC, Jlu18 submitted a review, later dismissed

2023-02-05 19:57 UTC, closed without merging